spring.application.name=payment-event-ledger-eos
server.port=${PORT:4337}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.jackson.serialization.indent_output=true
